# Generated by Django 4.2.3 on 2023-07-23 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id_con', models.AutoField(primary_key=True, serialize=False)),
                ('peso_con', models.IntegerField()),
                ('altura_con', models.CharField(max_length=100)),
                ('nota_con', models.TextField()),
                ('consultorio_estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id_hora', models.AutoField(primary_key=True, serialize=False)),
                ('inicio_hora', models.TimeField()),
                ('final_hora', models.TimeField()),
                ('horas_estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Representantes',
            fields=[
                ('id_rep', models.AutoField(primary_key=True, serialize=False)),
                ('representate_estado', models.BooleanField(default=True)),
                ('id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_pac', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pac', models.CharField(max_length=255)),
                ('nacimiento_pac', models.DateField()),
                ('genero_pac', models.CharField(max_length=20)),
                ('pacientes_pac', models.BooleanField(default=True)),
                ('id_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.representantes')),
            ],
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_lugar', models.CharField(max_length=255)),
                ('nombre_lugar', models.CharField(max_length=255)),
                ('lugares_estado', models.BooleanField(default=True)),
                ('id_hora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.horas')),
            ],
        ),
    ]
