# Generated by Django 4.2.3 on 2023-07-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representantes',
            old_name='representate_estado',
            new_name='representante_estado',
        ),
    ]
