# Generated by Django 4.2.3 on 2023-07-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_rename_representate_estado_representantes_representante_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_aut', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_aut', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
