# Generated by Django 4.2.3 on 2023-07-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_consultorio_nacimiento_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultorio',
            name='nacimiento_con',
        ),
    ]
