# Generated by Django 4.2.3 on 2023-07-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_remove_consultorio_nacimiento_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='nacimiento_con',
            field=models.DateField(null=True),
        ),
    ]
