# Generated by Django 4.2.3 on 2023-07-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrarSistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crearcuenta',
            old_name='usuario',
            new_name='username',
        ),
    ]
