# Generated by Django 4.2.3 on 2023-07-22 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrarSistema', '0002_rename_usuario_crearcuenta_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRoles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('es_usuario', models.BooleanField(default=True)),
                ('es_administrador', models.BooleanField(default=False)),
                ('es_programador', models.BooleanField(default=False)),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
