# Generated by Django 4.2.3 on 2023-07-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrarSistema', '0004_alter_usuarioroles_id_usu'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearcuenta',
            name='usuario_estado',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
